name: Node.js Package

on:
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: cd gerenciamento_tarefas_estudantis/backend && npm ci

      - name: Build
        run: cd gerenciamento_tarefas_estudantis/backend && npm run-script build

      - name: Test
        run: cd gerenciamento_tarefas_estudantis/backend && npm test

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: cd gerenciamento_tarefas_estudantis/frontend && npm ci

      - name: Build
        run: cd gerenciamento_tarefas_estudantis/frontend && npm run-script build

      - name: Test
        run: cd gerenciamento_tarefas_estudantis/frontend && npm test

  publish-npm:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: cd gerenciamento_tarefas_estudantis/backend && npm ci

      - name: Build
        run: cd gerenciamento_tarefas_estudantis/backend && npm run-script build

      - name: Test
        run: cd gerenciamento_tarefas_estudantis/backend && npm test

      - name: Publish to npm
        run: cd gerenciamento_tarefas_estudantis/backend && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
